const { withAppBuildGradle } = require('expo/config-plugins');

/**
 * Adds a real `release` signing config to the generated Android project.
 *
 * `android/` is regenerated by `expo prebuild`, so hand-editing build.gradle
 * would be wiped on every CI run. This plugin re-applies the change each time.
 *
 * The credentials come from Gradle properties, which CI writes into
 * `android/gradle.properties` (see codemagic.yaml):
 *
 *   WEAO_STORE_FILE, WEAO_STORE_PASSWORD, WEAO_KEY_ALIAS, WEAO_KEY_PASSWORD
 *
 * When they are absent the release build falls back to the debug key, so a
 * local `assembleRelease` still produces an installable APK.
 */

const MARKER = '// weao: release signing';
const SPLIT_MARKER = '// weao: abi splits';

const SIGNING_CONFIG = `
        release {
            ${MARKER}
            if (project.hasProperty('WEAO_STORE_FILE')) {
                storeFile file(WEAO_STORE_FILE)
                storePassword WEAO_STORE_PASSWORD
                keyAlias WEAO_KEY_ALIAS
                keyPassword WEAO_KEY_PASSWORD
            } else {
                // No upload key configured: fall back to the debug keystore so
                // assembleRelease still yields a sideloadable APK. Such a build
                // cannot be published to Play.
                storeFile file('debug.keystore')
                storePassword 'android'
                keyAlias 'androiddebugkey'
                keyPassword 'android'
            }
        }`;

function addSigningConfig(contents) {
  if (contents.includes(MARKER)) return contents;

  // Append a `release` block inside the existing signingConfigs { ... }.
  const anchor = contents.indexOf('signingConfigs {');
  if (anchor === -1) {
    throw new Error('withReleaseSigning: no signingConfigs block in app/build.gradle');
  }
  const insertAt = contents.indexOf('\n', anchor);
  return contents.slice(0, insertAt) + SIGNING_CONFIG + contents.slice(insertAt);
}

/**
 * Emits one APK per CPU architecture instead of a single fat one.
 *
 * A universal build carries native libraries for all four ABIs, two of which
 * (x86, x86_64) only ever run in an emulator. Splitting drops a real device's
 * download from ~106 MB to ~40 MB.
 *
 * `universalApk false` means no combined APK is produced; publish the
 * arm64-v8a build for modern phones and armeabi-v7a for older 32-bit ones.
 */
const SPLITS_BLOCK = `
    splits {
        abi {
            ${SPLIT_MARKER}
            enable true
            reset()
            include 'arm64-v8a', 'armeabi-v7a'
            universalApk false
        }
    }
`;

function addAbiSplits(contents) {
  if (contents.includes(SPLIT_MARKER)) return contents;
  const anchor = contents.indexOf('android {');
  if (anchor === -1) throw new Error('withReleaseSigning: no android block in app/build.gradle');
  const insertAt = contents.indexOf('\n', anchor);
  return contents.slice(0, insertAt) + SPLITS_BLOCK + contents.slice(insertAt);
}

function useReleaseSigningForReleaseBuild(contents) {
  // Expo's template points the release build type at the debug key. Repoint it,
  // but only that one occurrence inside buildTypes.release.
  return contents.replace(
    /(buildTypes\s*\{[\s\S]*?release\s*\{[\s\S]*?signingConfig\s+signingConfigs\.)debug/,
    '$1release',
  );
}

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error('withReleaseSigning: expected a Groovy build.gradle');
    }
    let contents = addSigningConfig(cfg.modResults.contents);
    contents = useReleaseSigningForReleaseBuild(contents);
    contents = addAbiSplits(contents);
    cfg.modResults.contents = contents;
    return cfg;
  });
};
